### ISSUE TITLE
Clean up and reformat the instructions for getting started

### ISSUE THREAD

**Issue by gautamkrishnar** [RITct/RITSoft#1]
Clean up the readme, reformat it to markdown format. Correct the grammatical and spelling mistakes if any.

**Comment by gautamkrishnar** [comment]
We need to correct the documentation to use `docker compose up -d` command instead of all the docker commands in the current readme. Remove all the unwanted info after consulting the https://github.com/RITct/RITSoft/blob/master/docker-compose.yml

**Comment by dravog7** [comment]
let me try this issue.
